spring.application.name=apiCardapioMobile
spring.jpa.hibernate.ddl-auto= validate
spring.datasource.url=jdbc:postgresql://localhost:5433/CardapioMobile
spring.datasource.username=murilo
spring.datasource.password=1921
spring.jpa.show-sql=true

